version: "3.9"

services:
  frontend:
    build: .
    container_name: marketing_frontend
    restart: always

    command: npm run dev

    ports:
      - "3005:3000"

    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8005

    dns:
      - 8.8.8.8
